/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.soma;

import javax.swing.JOptionPane;

/**
 *
 * @author sn1093554
 */
public class FrmSoma extends javax.swing.JFrame {

    /**
     * Creates new form FrmSoma
     */
    public FrmSoma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblProjetoSoma = new javax.swing.JLabel();
        lblValor01 = new javax.swing.JLabel();
        lblValor02 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtValor02 = new javax.swing.JTextField();
        txtValor01 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalcular.setBackground(new java.awt.Color(0, 0, 255));
        btnCalcular.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 40));

        btnLimpar.setBackground(new java.awt.Color(0, 0, 204));
        btnLimpar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 190, 110, 40));

        lblProjetoSoma.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblProjetoSoma.setText("Projeto Soma");
        getContentPane().add(lblProjetoSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, -1));

        lblValor01.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblValor01.setText("Valor 01:");
        getContentPane().add(lblValor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblValor02.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblValor02.setText("Valor 02:");
        getContentPane().add(lblValor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lblTotal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtTotal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 337, -1));

        txtValor02.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txtValor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 337, -1));

        txtValor01.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txtValor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 337, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
      
        //1 passo - Declarar Variaveis
        double v1, v2, total;
        
        //2 passo - Entrada
        v1 = Double.parseDouble(txtValor01.getText());
        v2 = Double.parseDouble(txtValor02.getText());
        
        //3 passo - Processamento
        total = v1 + v2;
        
        //4 passo - Saída
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        //Botao limpar
        txtValor01.setText(null);
        txtValor02.setText(null);
        txtTotal.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblProjetoSoma;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor01;
    private javax.swing.JLabel lblValor02;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValor01;
    private javax.swing.JTextField txtValor02;
    // End of variables declaration//GEN-END:variables
}
